# Dependency Review Configuration
# Vulnerability settings
fail_on_severity: 'high'           # Options: low, moderate, high, critical
vulnerability_check: true          # Enable/disable vulnerability checking
warn_only: false                   # Set to true to only warn, not fail

# License settings (choose ONE - allow_licenses OR deny_licenses)
license_check: true  
# OpenSSF Scorecard configuration
fail-on-openssf-scorecard-threshold: 2.0

# Allow these specific packages with lower scores, they are widely used and maintained
allow-dependencies-licenses:
  - MIT
  - Apache-2.0
  - BSD-2-Clause
  - BSD-3-Clause
  - ISC

# Only fail on runtime dependencies, not dev dependencies
fail-on-scopes:
  - runtime

# Allow these specific packages that have lower OpenSSF scores but are essential
allow-dependencies:
  - uri-js
  - type-check
  - prelude-ls
  - levn
  - isexe
  - cross-spawn
