import React from "react";
import { useState, useEffects } from "react";
import { Loader, Card, FormField } from "../components";

const Home = () => {
  const [loading, setLoading] = useState(false);
  const [allPosts, setAllPosts] = useState(null);

  return (
    <section className="max-w-7x1 mx-auto">
      <div>
        <h1 className="font-extrabold text-[#222328] text-[32px]">
          The Community Showcase
        </h1>
        <p className="mt-2 text-[#666e75] text-[16px] max-w[500px]">
          Browse though a collection of amazing imaginative images generated by
          AI.
        </p>
      </div>

      <div className='mt-16'>
        <FormField />
      </div>

    </section>
  );
};

export default Home;
