name: Full-Stack CI/CD Pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
permissions:
  contents: read
  pull-requests: write
  packages: write # Required for pushing Docker images to GitHub Packages

jobs:
  # ----------------------------------------------------
  # Job 1: Build and Test the Client (React App)
  # ----------------------------------------------------
  client_build_and_test:
    name: Build & Test Client
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install root dependencies (Jest and test tools)
        run: npm ci
        working-directory: .

      - name: Install client dependencies
        run: npm ci
        working-directory: client

      - name: Run ESLint on client
        run: npm run lint
        working-directory: client

      - name: Run Jest tests with coverage on client
        run: npm run test:coverage -- --selectProjects=client
        working-directory: .

      - name: Build client
        run: npm run build
        working-directory: client

      - name: Upload client coverage reports
        uses: actions/upload-artifact@v4
        with:
          name: client-coverage
          path: coverage/
          retention-days: 7
        if: always()

      - name: Upload client build artifact
        uses: actions/upload-artifact@v4
        with:
          name: client-build-artifact
          path: client/dist/

  # ----------------------------------------------------
  # Job 2: Build and Push the Server Docker Image
  # ----------------------------------------------------
  server_build_and_push:
    name: Build & Push Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install root dependencies (Jest and test tools)
        run: npm ci
        working-directory: .

      - name: Install server dependencies
        run: npm ci
        working-directory: server

      - name: Run ESLint on server
        run: npm run lint
        working-directory: server

      - name: Run Jest tests on server
        run: npm run test:server

      - name: Run Jest tests with coverage on server
        run: npm run test:coverage -- --selectProjects=server
        working-directory: .
        
      - name: Upload server coverage reports  
        uses: actions/upload-artifact@v4
        with:
          name: server-coverage
          path: coverage/
          retention-days: 7
        if: always()

      # Log in to a container registry Docker Hub or GitHub Packages
      - name: Login to Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push the Docker image for the server
      - name: Build and push server image
        uses: docker/build-push-action@v4
        with:
          context: server/
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/aiimagegen-server:latest

  # ----------------------------------------------------
  # Job 3: Deploy the Full-Stack Application
  # ----------------------------------------------------
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [client_build_and_test, server_build_and_push]
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download client build artifact
        uses: actions/download-artifact@v4
        with:
          name: client-build-artifact
          path: client/dist/

      # The client deployment AWS would use the downloaded artifact
      - name: Deploy to Production
        run: echo "Deployment to production is now ready. Add your deployment script here."
        env:
          MONGODB_URL: ${{ secrets.MONGODB_URL }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
          CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
          CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}