name: "Dependency Review"

on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write
  security-events: write
  actions: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4

      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          # Scanning for vulnerabilities
          vulnerability-check: true
          # Fail on high severity issues
          fail-on-severity: high
          # Add PR comment summary
          comment-summary-in-pr: true